#!/bin/sh

# Stanford input data conversions:
# - Change file extensions from .rdf.xml to .rdf
# - Pretty-print the rdfxml into subdirectory rdfxml
# - Convert rdfxml to ntriples into subdirectory ntriples
# Run from directory containing files

jar=$1
mkdir rdfxml
mkdir ntriples
echo "Created subdirectory rdfxml for pretty-printed rdf, and ntriples for nt files"

for file in *.rdf.xml; do

    prettyprinted="${file/%.rdf.xml/.rdf}"
    echo "Pretty-printing ${file} to ${prettyprinted}..."
    xmllint --format ${file} > "${prettyprinted}"

    echo "Converting ${prettyprinted} from rdfxml to ntriples..."
    `java -jar ${jar} ${prettyprinted} .nt`  

    mv ${prettyprinted} rdfxml
    mv "${prettyprinted/%.rdf/.nt}" ntriples

done
    